version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-list-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=todo_user
      - DATABASE_PASSWORD=todo_password
      - DATABASE_NAME=todo_list
      - JWT_SECRET=your_jwt_secret_key
    restart: unless-stopped
    networks:
      - todo-network

  db:
    image: mariadb:10.6
    container_name: todo-list-db
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_DATABASE=todo_list
      - MARIADB_USER=todo_user
      - MARIADB_PASSWORD=todo_password
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  db_data:
    driver: local